version: '3.9'

services:
  tax_api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args: 
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app
    command: python3 manage.py runserver 0.0.0.0:8000
